//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKTGT.PTD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PtdKhoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PtdKhoa()
        {
            this.PtdSV = new HashSet<PtdSV>();
        }
    
        public string PtdMaKH { get; set; }
        public string PtdTenKh { get; set; }
        public Nullable<bool> PtdTrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PtdSV> PtdSV { get; set; }
    }
}
