//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKTGT.PTD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PtdSV
    {
        public string PtdMaSV { get; set; }
        public string PtdHoSV { get; set; }
        public string PtdTenSV { get; set; }
        public Nullable<System.DateTime> PtdNgaySinh { get; set; }
        public Nullable<bool> PtdPhai { get; set; }
        public string PtdPhone { get; set; }
        public string Ptdmail { get; set; }
        public string PtdMaKH { get; set; }
    
        public virtual PtdKhoa PtdKhoa { get; set; }
    }
}
